name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        #cache: gradle 
        
    - name: Setup Gradle 
      uses: gradle/gradle-build-action@v2 
      with: 
        gradle-version: 6.8.3
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew
      
    - name: Running unit tests with Gradlew 
      run: ./gradlew test 
      
    - name: Running acceptance tests with Gradlew 
      run: ./gradlew acceptanceTest
