name: fitNesse CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        #cache: gradle 
        
    
    - name: Setup Gradle 
      uses: gradle/gradle-build-action@v2 
      with: 
        gradle-version: 7.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew
    - name: Running unit tests with Gradlew 
      run: ./gradlew test 
    - name: Running acceptance tests with Gradlew 
      run: ./gradlew acceptanceTest
